include ../build/makefiles/makefile.master

OBJS = keyboard.o scancodes.o

OBJSO = $(addprefix $(OBJPREFIX)/, $(OBJS))

CFLAGS+= -I../include -I../include/libs

all: objdirs $(OBJSO)
	$(AR) $(OBJPREFIX)_devices.a $(OBJSO)

clean:
	rm -rf $(OBJSO) *.a
