include $(WSROOT)/build/makefiles/makefile.master

OBJS = keyboard.o scancodes.o

OBJSO = $(addprefix $(OBJPREFIX)/, $(OBJS))

all: objdirs $(OBJSO)
	$(AR) $(OBJPREFIX)_devices.a $(OBJSO)

clean:
	rm -rf $(OBJSO) *.a
