include ../build/makefiles/makefile.master

all:
	cd null && make all
	cd N9H26 && make all
	$(AR) $(OBJPREFIX)_drivers.a null/$(OBJPREFIX)/null.o N9H26/$(OBJPREFIX)_drivers.a

clean:
	cd null && make clean
	cd N9H26 && make clean
	rm -rf *.a
