include $(WSROOT)/build/makefiles/makefile.master

OBJS =  

OBJSO = $(addprefix $(OBJPREFIX)/, $(OBJS))
 
all: objdirs $(OBJSO)
	cd pci && make all
	$(AR) $(OBJPREFIX)_libkernel.a $(OBJSO)
	
clean:
	cd pci && make clean
